---
title: "Dustin's Work"
author: "Dustin"
format: 
  html:
    code-fold: show
    toc: true
    number-sections: true
    embed-resources: true
editor: visual
execute:
  echo: true
  message: false
  warning: false
---

```{r}
#| message: false
# Loading all my packages 
rm(list = ls())
library(tidyverse)
library(here)
library(sf) # Vector spatial data
library(terra) # Raster spatial data
library(tidyterra) # For rasters in GGplot
library(gstat)
library(stars)
library(broom)
library(tmap)
library(spatstat)
library(patchwork)
library(stringr)

```

```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  stars, # spatiotemporal data handling
  terra, # raster data handling
  raster, # raster data handling
  sf, # vector data handling
  dplyr, # data wrangling
  stringr, # string manipulation
  lubridate, # dates handling
  data.table, # data wrangling
  tidyr, # reshape
  tidyUSDA, # download USDA NASS data
  keyring, # API key management
  FedData, # download Daymet data
  daymetr, # download Daymet data
  ggplot2, # make maps
  tmap, # make maps
  future.apply, # parallel processing
  CropScapeR, # download CDL data
  prism, # download PRISM data
  exactextractr # extract raster values to sf --> i.e. zonal statistics 
)
```


# Loading data in a reasonable format and doing necessary switcheroos for my plot 

```{r}
########################### AHUPUAA .SHP FILE ################################# 
## Loading ahupuaa .shp file as 'data'
data <- st_read(here::here("data", "ahupuaa","ahupuaa.shp")) %>% 
  janitor::clean_names()

## Obtaining the layers from the ahupuaa .shp file 
st_layers(dsn = here::here("data", "ahupuaa","ahupuaa.shp"))

## Converting .shp file to a simple features collection
data_sf <- st_as_sf(data) # --> EPSG 3750

## Reprojecting data to WGS84 
(
data_new_sf <- st_transform(data, 4326)
)
## Checking coordinate reference system 
st_crs(data_new_sf)

## Converting the wack apostrophies and other characters to ones R can recognize
data_sf_clean <- data_new_sf %>% 
  mutate(moku = str_replace_all(moku, pattern = "ʻ", replacement = "'"),
         mokupuni = str_replace_all(mokupuni, pattern = "ʻ", replacement = "'"),
         ahupuaa = str_replace_all(ahupuaa, pattern = "ʻ", replacement = "'"),
         ahupuaa = str_replace_all(ahupuaa, pattern = "ā", replacement = "a"),
         ahupuaa = str_replace_all(ahupuaa, pattern = "ī", replacement = "i"),
         ahupuaa = str_replace_all(ahupuaa, pattern = "ï", replacement = "i"),
         ahupuaa = str_replace_all(ahupuaa, pattern = "ō", replacement = "o"),
         ahupuaa = str_replace_all(ahupuaa, pattern = "ē", replacement = "e"),
         ahupuaa = str_replace_all(ahupuaa, pattern = "ū", replacement = "u"),
         ahupuaa = str_replace_all(ahupuaa, pattern = "Ï", replacement = "I"),
         ahupuaa = str_replace_all(ahupuaa, pattern = "Ō", replacement = "O"),
         ahupuaa = str_replace_all(ahupuaa, pattern = "Ā", replacement = "A")) %>%
  mutate(moku = ifelse(
    ahupuaa == "Kiauea", "Ko'olau", moku),
    mokupuni = ifelse(ahupuaa == "Kiauea" & moku == "Ko'olau", "Kaua'i", mokupuni
      
    )) %>% 
  janitor::clean_names()

## Rasterizing data_sf_clean (just in case )
(
data_rast <- rast(data_sf_clean)
)

## Vectorizing data_sf_clean 
data_vec <- vect(data_sf_clean)

# Filtering data to just hawaii (checking)
data_vec_hawaii <- data_sf_clean %>% filter( mokupuni == "Hawai'i") 
# Vectorizing it 
vect(data_vec_hawaii)


################################ FOOD .TIF FILE ###############################

## Loads it as a value and then rasterizing it makes it a SpatRaster
food_file <- here::here("data", "food_priority1.tif")

## Loads it directly as a RasterStack object
# (
# food_rs <- stack(here::here("data", "food_priority1.tif"))
# )

## Checking CRS 
# terra::crs(food_rs)

## Reprojecting food raster to WGS 84 
# food_rs_WGS84 <- st_transform(food_rs, 4326)

## Rasterizing food_file --> Turns to SpatRaster
(
food_rs <- rast(food_file)
)

## Tells us that the raster is projected in WGS 84 
# terra::crs(food_data)

## Turning food raster into a dataframe for plotting purposes 
food_df <- as.data.frame(food_rs, xy = TRUE) %>% 
  na.omit() %>% 
  mutate(Food = as.character(Food))

################################ CARBON .TIF FILE #############################

## Loads it as a value and then rasterizing it makes it a SpatRaster
carbon_file <- here("data", "carbon_priority2.tif")

## Rasterizing carbon_file --> Turns to SpatRaster
(
carbon_rs <- rast(carbon_file)
)

## Turning carbon raster into a dataframe for plotting purposes
carbon_df <- as.data.frame(carbon_rs, xy = TRUE) %>% 
  na.omit() %>% 
  mutate(Carbon = as.character(Carbon))

############################## MULTI-LAYER .TIF FILE ##########################

## Loading both carbon and food files as a list
files_list <- here::here(c("data/food_priority1.tif", "data/carbon_priority2.tif"))

## Rasterizing them --> Same rows and columns, but two layers 
(
  multi_layer_rs <- rast(files_list)
)

## Converting the raster to polygons 
multi_layer_polygons <- as.polygons(multi_layer_rs)

## Converting polygons to sf 
multi_layer_sf <- st_as_sf(multi_layer_polygons)


(
data_resample <- terra::resample(data_rast, multi_layer_rs, method='bilinear')
)


multi_layer_df_food <- as.data.frame(multi_layer_rs, xy = TRUE) %>%
  filter(Food == 1 & Carbon == 0)

multi_layer_df_carbon <- as.data.frame(multi_layer_rs, xy = TRUE) %>%
  filter(Food == 0 & Carbon == 1) 

## Send this down after loading the multi_layers_sr 
values <- extract(multi_layer_rs, data_vec, fun = max, na.rm = TRUE)

########################### LAND USE COVER DATA ###############################

# Success he thinks it will be useful! 
(
landuse <- st_read(here::here("/Users/dustinduncan/Desktop/ESM 244/Land_Use_Land_Cover_(LULC)/Land_Use_Land_Cover_(LULC).shp")) 
)
landuse_sf <- st_as_sf(landuse) %>% 
  mutate(landcover = as.factor(landcover)) %>% 
  mutate(coverstring = case_when(
    landcover == "0" ~ "No classification",
    landcover == "11" ~ "Residential",
    landcover == "12" ~ "Commercial and services",
    landcover == "13" ~ "Industrial",
    landcover == "14" ~ "Transportation, Communications, and Utilities",
    landcover == "15" ~ "Industrial and Commercial Complexes",
    landcover == "16" ~ "Mixed Urban or Built-up Land",
    landcover == "17" ~ "Other Urban or Built-up land",
    landcover == "21" ~ "Cropland and Pasture",
    landcover == "22" ~ "Orchards, Groves, Vineyards, Nurseries and Ornamental Horticultural Areas",
    landcover == "23" ~ "Confined Feeding Operations",
    landcover == "24" ~ "Other Agricultural Land",
    landcover == "31" ~ "Herbaceous Rangeland",
    landcover == "32" ~ "Shrub and Brush Rangeland",
    landcover == "33" ~ "Mixed Rangeland",
    landcover == "42" ~ "Evergreen Forest Land",
    landcover == "51" ~ "Streams and Canals",
    landcover == "52" ~ "Lakes",
    landcover == "53" ~ "Reservoirs",
    landcover == "54" ~ "Bays and Estuaries",
    landcover == "61" ~ "Forested Wetland",
    landcover == "62" ~ "Nonforested Wetland",
    landcover == "72" ~ "Beaches",
    landcover == "73" ~ "Sandy Areas other than Beaches",
    landcover == "74" ~ "Bare Exposed Rock",
    landcover == "75" ~ "Strip Mines, Quarries, and Gravel Pits",
    landcover == "76" ~ "Transitional Areas",
    landcover == "77" ~ "Mixed Barren Land"
  )) %>% 
  mutate(coverstring = as.character(coverstring)) %>% 
  mutate(resample = case_when(
    landcover == "0" ~ "No classification",
    landcover == "11" ~ "Residential",
    landcover == "12" ~ "Industrial or Commercial",
    landcover == "13" ~ "Industrial or Commercial",
    landcover == "14" ~ "Transportation",
    landcover == "15" ~ "Industrial or Commercial",
    landcover == "16" ~ "Urban",
    landcover == "17" ~ "Urban",
    landcover == "21" ~ "Agriculture",
    landcover == "22" ~ "Agriculture",
    landcover == "23" ~ "Confined Feeding Operations",
    landcover == "24" ~ "Agriculture",
    landcover == "31" ~ "Rangeland",
    landcover == "32" ~ "Rangeland",
    landcover == "33" ~ "Rangeland",
    landcover == "42" ~ "Evergreen Forest",
    landcover == "51" ~ "Water Body",
    landcover == "52" ~ "Water Body",
    landcover == "53" ~ "Water Body",
    landcover == "54" ~ "Water Body",
    landcover == "61" ~ "Wetland",
    landcover == "62" ~ "Wetland",
    landcover == "72" ~ "Beaches",
    landcover == "73" ~ "Sandy Areas other than Beaches",
    landcover == "74" ~ "Barren or Unusable land",
    landcover == "75" ~ "Barren or Unusable land",
    landcover == "76" ~ "Urban",
    landcover == "77" ~ "Barren or Unusable land",
  )) %>% 
  mutate(resample = as.factor(resample))

landuse_vec <- vect(landuse_sf)

 # st_crs(landuse_sf) # --> EPSG 4326

ggplot() + 
  geom_sf(data = landuse_sf, aes(fill = resample, color = resample)) + 
  theme(legend.position = "none")
  

ggplot(data_sf_clean) +
  stat_sf_coordinates()

ggplot(data_sf_clean) +
  geom_errorbarh(
    aes(geometry = geometry,
        xmin = after_stat(x) - 0.1,
        xmax = after_stat(x) + 0.1,
        y = after_stat(y),
        height = 0.04),
    stat = "sf_coordinates"
  )

ggplot() + 
  geom_sf(data = data_sf_clean)
```
## Intersecting land use coverage data with ahupuaa data 

```{r}
class(landuse_sf)
class(data_sf_clean)
sf_use_s2(FALSE)
# data_landuse_sf <- st_union(data_sf_clean, landuse_sf, by_feature = geometry)

ggplot() + 
  geom_sf(data = landuse_sf, aes(fill = resample, color = resample)) +
  geom_sf(data = data_sf_clean, color = "black", fill = NA) +
  theme(legend.position = "none")
```


## Plotting Food and Carbon rasters and cropping to filtered ahupuaa data 

```{r}
# Cropping my multi-layer spatraster to the extent of my filtered vector 
multi_layer_hawaii_rs <- crop(multi_layer_rs, extent(data_vec_hawaii))
# Converting my cropped multi_layer_ras__hawaii raster to a dataframe 
multi_layer_hawaii_df <- as.data.frame(multi_layer_hawaii_rs, xy = TRUE)
# Cropping my land use vector to the extent of my filtered vector
landuse_hawaii_sf <- st_crop(landuse_sf, data_vec_hawaii)

# PLotting it over the file vector 
ggplot() +
  geom_sf(data = landuse_hawaii_sf, aes(fill = resample)) + 
  geom_sf(data = data_vec_hawaii, fill = NA, color = "black") +
  geom_tile(data = multi_layer_hawaii_df, inherit.aes = FALSE, aes(x = x, y = y), fill = "#882222")  
  theme(legend.position = "none")

## Save this one for later 
data_vec_hawaii_kona <- data_vec_hawaii %>% 
  filter(moku == "Kona" | moku == "Hilo")
vect(data_vec_hawaii_kona)
multi_layer_hawaii_kona_rs <- crop(multi_layer_rs, extent(data_vec_hawaii_kona))
multi_layer_hawaii_kona_df <- as.data.frame(multi_layer_hawaii_kona_rs, xy = TRUE)
landuse_hawaii_kona_sf <- st_crop(landuse_sf, data_vec_hawaii_kona)

ggplot() +
  # geom_sf(data = landuse_hawaii_kona_sf, aes(fill = resample)) +
  geom_sf(data = data_vec_hawaii_kona, fill = NA, color = "black") +
  geom_tile(data = multi_layer_hawaii_kona_df, inherit.aes = FALSE, aes(x = x, y = y), fill = "#882222") + 
  theme(legend.position = "none")

## Now doing O'ahu
data_vec_oahu <- data_sf_clean %>% 
  filter(mokupuni == "O'ahu")
vect(data_vec_oahu)
multi_layer_oahu_rs <- crop(multi_layer_rs, extent(data_vec_oahu))
multi_layer_oahu_df <- as.data.frame(multi_layer_oahu_rs, xy = TRUE)
landuse_oahu_sf <- st_crop(landuse_sf, data_vec_oahu)
ggplot() +
  geom_sf(data = landuse_oahu_sf, aes(fill = resample)) +
  geom_sf(data = data_vec_oahu, fill = NA, color = "black" ) +
  geom_tile(data = multi_layer_oahu_df, inherit.aes = FALSE, aes(x = x, y = y), fill = "#882222")

## Now doing Maui County
data_vec_maui <- data_sf_clean %>% 
  filter(mokupuni == "Maui" | mokupuni == "Moloka'i" | mokupuni == "Lāna'i" | mokupuni == "Kaho'olawe" | mokupuni == "Molokini")
vect(data_vec_maui)
multi_layer_maui_rs <- crop(multi_layer_rs, extent(data_vec_maui))
multi_layer_maui_df <- as.data.frame(multi_layer_maui_rs, xy = TRUE) 
landuse_maui_sf <- st_crop(landuse_sf, data_vec_maui)

ggplot() +
  geom_sf(data = landuse_maui_sf, aes(fill = resample)) +
  geom_sf(data = data_vec_maui, fill = NA, color = "black" ) +
  geom_tile(data = multi_layer_maui_df, inherit.aes = FALSE, aes(x = x, y = y), fill = "#882222", alpha = 0.5)

## Now doing Kauai
data_vec_kauai <- data_sf_clean %>% 
  filter(mokupuni == "Kaua'i" | mokupuni == "Ni'ihau")
# vect(data_vec_kauai)
multi_layer_kauai_rs <- crop(multi_layer_rs, extent(data_vec_kauai))
multi_layer_kauai_df <- as.data.frame(multi_layer_kauai_rs, xy = TRUE)
landuse_kauai_sf <- st_crop(landuse_sf, data_vec_kauai)
ggplot() +
  geom_sf(data = landuse_kauai_sf, aes(fill = resample)) +
  geom_sf(data = data_vec_kauai, fill = NA, color = "black" ) +
  geom_tile(data = multi_layer_kauai_df, inherit.aes = FALSE, aes(x = x, y = y), fill = "#882222")

## Now doing Ni'ihau
data_vec_niihau <- data_sf_clean %>% 
  filter(mokupuni == "Ni'ihau")
vect(data_vec_niihau)
# multi_layer_niihau_rs <- crop(multi_layer_rs, extent(data_vec_niihau))
# multi_layer_niihau_df <- as.data.frame(multi_layer_niihau_rs, xy = TRUE)
landuse_niihau_sf <- st_crop(landuse_sf, data_vec_niihau)
ggplot() +
  geom_sf(data = landuse_niihau_sf, aes(fill = resample)) +
  geom_sf(data = data_vec_niihau, fill = NA, color = "black" )
# +
  # geom_tile(data = multi_layer_niihau_df, inherit.aes = FALSE, aes(x = x, y = y), fill = "#882222")

# Plotting my different rasters that are selected for food = 1 and carbon = 1 over the islands data 
ggplot() +
  geom_sf(data = data_vec, fill = "lightblue") +
  geom_tile(data = multi_layer_df_food, inherit.aes = FALSE, aes(x = x, y = y), fill = "green") + 
  geom_tile(data = multi_layer_df_carbon, aes(x = x, y = y), fill = "#882222", alpha = 0.5) +
  scale_fill_manual(values = c("Carbon" = "#882222", "Food" = "green"))
  # geom_sf(data = multi_layer_sf, )
  # geom_spatraster(data = multi_layer_rs,aes(fill = Carbon)) 
  



# terra::writeRaster(multi_layer_rs, "data/food_carbon_stack.tif", filetype = "GTiff", overwrite = TRUE)
```


## Plotting food data frame 

```{r}
food_df1 <- food_df %>% 
  filter(Food == 1)
food_df0 <- food_df %>% 
  filter(Food == 0)

ggplot(data = food_df1) + 
  geom_tile(aes(x = x, y = y), fill = "#882222") + 
  coord_equal() + 
  theme_dark()

ggplot(data = food_df0) + 
  geom_tile(aes(x = x, y = y), fill = "green") +
  coord_equal() + 
  theme_dark()

food_df_plot <- ggplot(data = food_df) + 
  geom_tile(aes(x = x, y = y, fill = Food)) + 
  scale_fill_manual(values = c("green", "#882222")) + 
  coord_equal() + 
  theme_dark()

food_df_plot
  

# f <- plot(food_data)
# rect(par("usr")[1], par("usr")[3],
#      par("usr")[2], par("usr")[4],
#      col = "#8F8F8F")
# par(new = TRUE)
# f2 <- plot(food_data)
```





```{r}
carbon_df1 <- carbon_df %>% 
  filter(Carbon == 1)
carbon_df0 <- carbon_df %>% 
  filter(Carbon == 0)
ggplot(data = carbon_df1) + 
  geom_tile(aes(x = x, y = y), fill = "#882222") + 
  coord_equal() + 
  theme_dark()

ggplot(data = carbon_df0) + 
  geom_tile(aes(x = x, y = y), fill = "green") +
  coord_equal() + 
  theme_dark()


carbon_df_plot <- ggplot(data = carbon_df) + 
  geom_tile(aes(x = x, y = y, fill = Carbon)) + 
  scale_fill_manual(values = c("green", "#882222")) + 
  coord_equal() + 
  theme_dark()

carbon_df_plot

```


Global.r and .rm file into the ui.r 








