---
title: "Pioneer Mill Text Analysis"
format: html
editor: visual
---

```{r setup}
library(tidyverse)
library(tidytext)
library(pdftools)
library(ggwordcloud)
```

## Get text of the Interviews

```{r}
intrvw_1 <- pdftools::pdf_text(here::here('data','Pioneer Mill Interviews', 'pioneermill_03.pdf'))
intrvw_2 <- pdftools::pdf_text(here::here('data', 'Pioneer Mill Interviews','pioneermill_04.pdf'))
intrvw_3 <- pdftools::pdf_text(here::here('data', 'Pioneer Mill Interviews', 'pioneermill_05.pdf'))
intrvw_4 <- pdftools::pdf_text(here::here('data','Pioneer Mill Interviews', 'pioneermill_06.pdf'))
intrvw_5 <- pdftools::pdf_text(here::here('data', 'Pioneer Mill Interviews','pioneermill_07.pdf'))
intrvw_6 <- pdftools::pdf_text(here::here('data', 'Pioneer Mill Interviews','pioneermill_08.pdf'))
intrvw_7 <- pdftools::pdf_text(here::here('data','Pioneer Mill Interviews', 'pioneermill_09.pdf'))
intrvw_8 <- pdftools::pdf_text(here::here('data', 'Pioneer Mill Interviews','pioneermill_10.pdf'))
intrvw_9 <- pdftools::pdf_text(here::here('data', 'Pioneer Mill Interviews','pioneermill_11.pdf'))
intrvw_10 <- pdftools::pdf_text(here::here('data', 'Pioneer Mill Interviews','pioneermill_12.pdf'))
intrvw_11 <- pdftools::pdf_text(here::here('data', 'Pioneer Mill Interviews','pioneermill_13.pdf'))
intrvw_12 <- pdftools::pdf_text(here::here('data', 'Pioneer Mill Interviews','pioneermill_14.pdf'))
intrvw_13 <- pdftools::pdf_text(here::here('data', 'Pioneer Mill Interviews','pioneermill_15.pdf'))
intrvw_14 <- pdftools::pdf_text(here::here('data', 'Pioneer Mill Interviews','pioneermill_16.pdf'))
intrvw_15 <- pdftools::pdf_text(here::here('data', 'Pioneer Mill Interviews','pioneermill_17.pdf'))
intrvw_16 <- pdftools::pdf_text(here::here('data', 'Pioneer Mill Interviews','pioneermill_18.pdf'))

```


```{r}
lines_1 <- data.frame(intrvw_1) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(intrvw_1, pattern = '\\n')) %>% 
  unnest(text_full) %>% ## turns lines on the page and "pivot longer"
  mutate(text_full = str_trim(text_full)) ## gets ride of white space 

lines_2 <- data.frame(intrvw_2) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(intrvw_2, pattern = '\\n')) %>% 
  unnest(text_full) %>% ## turns lines on the page and "pivot longer"
  mutate(text_full = str_trim(text_full)) ## gets ride of white space 


lines_3 <- data.frame(intrvw_3) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(intrvw_3, pattern = '\\n')) %>% 
  unnest(text_full) %>% ## turns lines on the page and "pivot longer"
  mutate(text_full = str_trim(text_full)) ## gets ride of white space 

lines_4 <- data.frame(intrvw_4) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(intrvw_4, pattern = '\\n')) %>% 
  unnest(text_full) %>% ## turns lines on the page and "pivot longer"
  mutate(text_full = str_trim(text_full)) ## gets ride of white space 

lines_5 <- data.frame(intrvw_5) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(intrvw_5, pattern = '\\n')) %>% 
  unnest(text_full) %>% ## turns lines on the page and "pivot longer"
  mutate(text_full = str_trim(text_full)) ## gets ride of white space 

lines_6 <- data.frame(intrvw_6) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(intrvw_6, pattern = '\\n')) %>% 
  unnest(text_full) %>% ## turns lines on the page and "pivot longer"
  mutate(text_full = str_trim(text_full)) ## gets ride of white space 

lines_7 <- data.frame(intrvw_7) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(intrvw_7, pattern = '\\n')) %>% 
  unnest(text_full) %>% ## turns lines on the page and "pivot longer"
  mutate(text_full = str_trim(text_full)) ## gets ride of white space 

lines_8 <- data.frame(intrvw_8) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(intrvw_8, pattern = '\\n')) %>% 
  unnest(text_full) %>% ## turns lines on the page and "pivot longer"
  mutate(text_full = str_trim(text_full)) ## gets ride of white space 

lines_9 <- data.frame(intrvw_9) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(intrvw_9, pattern = '\\n')) %>% 
  unnest(text_full) %>% ## turns lines on the page and "pivot longer"
  mutate(text_full = str_trim(text_full)) ## gets ride of white space 

lines_10 <- data.frame(intrvw_10) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(intrvw_10, pattern = '\\n')) %>% 
  unnest(text_full) %>% ## turns lines on the page and "pivot longer"
  mutate(text_full = str_trim(text_full)) ## gets ride of white space 

lines_11 <- data.frame(intrvw_11) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(intrvw_11, pattern = '\\n')) %>% 
  unnest(text_full) %>% ## turns lines on the page and "pivot longer"
  mutate(text_full = str_trim(text_full)) ## gets ride of white space 

lines_12 <- data.frame(intrvw_12) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(intrvw_12, pattern = '\\n')) %>% 
  unnest(text_full) %>% ## turns lines on the page and "pivot longer"
  mutate(text_full = str_trim(text_full)) ## gets ride of white space 

lines_13 <- data.frame(intrvw_13) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(intrvw_13, pattern = '\\n')) %>% 
  unnest(text_full) %>% ## turns lines on the page and "pivot longer"
  mutate(text_full = str_trim(text_full)) ## gets ride of white space 

lines_14 <- data.frame(intrvw_14) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(intrvw_14, pattern = '\\n')) %>% 
  unnest(text_full) %>% ## turns lines on the page and "pivot longer"
  mutate(text_full = str_trim(text_full)) ## gets ride of white space 

lines_15 <- data.frame(intrvw_15) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(intrvw_15, pattern = '\\n')) %>% 
  unnest(text_full) %>% ## turns lines on the page and "pivot longer"
  mutate(text_full = str_trim(text_full)) ## gets ride of white space 

lines_16 <- data.frame(intrvw_16) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(intrvw_16, pattern = '\\n')) %>% 
  unnest(text_full) %>% ## turns lines on the page and "pivot longer"
  mutate(text_full = str_trim(text_full)) ## gets ride of white space 

```


```{r}
words_1 <- lines_1 %>% 
  unnest_tokens(word, text_full) %>% 
  select(-intrvw_1)

words_2 <- lines_2 %>% 
  unnest_tokens(word, text_full) %>% 
  select(-intrvw_2)

words_3 <- lines_3 %>% 
  unnest_tokens(word, text_full) %>% 
  select(-intrvw_3)

words_4 <- lines_4 %>% 
  unnest_tokens(word, text_full) %>% 
  select(-intrvw_4)

words_5 <- lines_5 %>% 
  unnest_tokens(word, text_full) %>% 
  select(-intrvw_5)

words_6 <- lines_6 %>% 
  unnest_tokens(word, text_full) %>% 
  select(-intrvw_6)

words_7 <- lines_7 %>% 
  unnest_tokens(word, text_full) %>% 
  select(-intrvw_7)

words_8 <- lines_8 %>% 
  unnest_tokens(word, text_full) %>% 
  select(-intrvw_8)

words_9 <- lines_9 %>% 
  unnest_tokens(word, text_full) %>% 
  select(-intrvw_9)

words_10 <- lines_10 %>% 
  unnest_tokens(word, text_full) %>% 
  select(-intrvw_10)

words_11 <- lines_11 %>% 
  unnest_tokens(word, text_full) %>% 
  select(-intrvw_11)

words_12 <- lines_12 %>% 
  unnest_tokens(word, text_full) %>% 
  select(-intrvw_12)

words_13 <- lines_13 %>% 
  unnest_tokens(word, text_full) %>% 
  select(-intrvw_13)

words_14 <- lines_14 %>% 
  unnest_tokens(word, text_full) %>% 
  select(-intrvw_14)

words_15 <- lines_15 %>% 
  unnest_tokens(word, text_full) %>% 
  select(-intrvw_15)

words_16 <- lines_16 %>% 
  unnest_tokens(word, text_full) %>% 
  select(-intrvw_16)

```


```{r}
wordcount_1 <- words_1 %>% 
  count(word)

wordcount_2 <- words_2 %>% 
  count(word)

wordcount_3 <- words_3 %>% 
  count(word)

wordcount_4 <- words_4 %>% 
  count(word)

wordcount_5 <- words_5 %>% 
  count(word)

wordcount_6 <- words_6 %>% 
  count(word)

wordcount_7 <- words_7 %>% 
  count(word)

wordcount_8 <- words_8 %>% 
  count(word)

wordcount_9 <- words_9 %>% 
  count(word)

wordcount_10 <- words_10 %>% 
  count(word)

wordcount_11 <- words_11 %>% 
  count(word)

wordcount_12 <- words_12 %>% 
  count(word)

wordcount_13 <- words_13 %>% 
  count(word)

wordcount_14 <- words_14 %>% 
  count(word)

wordcount_15 <- words_15 %>% 
  count(word)

wordcount_16 <- words_16 %>% 
  count(word) 
  


```


```{r}
wc_clean_1 <- wordcount_1 %>% 
  anti_join(stop_words, by = 'word') %>% 
filter(word != 'hy') %>% 
  filter(word != 'jk')

wc_clean_2 <- wordcount_2 %>% 
  anti_join(stop_words, by = 'word') 

wc_clean_3 <- wordcount_3 %>% 
  anti_join(stop_words, by = 'word') 

wc_clean_4 <- wordcount_4 %>% 
  anti_join(stop_words, by = 'word') 
  

wc_clean_5 <- wordcount_5 %>% 
  anti_join(stop_words, by = 'word')

wc_clean_6 <- wordcount_6 %>% 
  anti_join(stop_words, by = 'word') 

wc_clean_7 <- wordcount_7 %>% 
  anti_join(stop_words, by = 'word') 

wc_clean_8 <- wordcount_8 %>% 
  anti_join(stop_words, by = 'word') 

wc_clean_9 <- wordcount_9 %>% 
  anti_join(stop_words, by = 'word') 

wc_clean_10 <- wordcount_10 %>% 
  anti_join(stop_words, by = 'word') %>% 
filter(word != 'mo') %>% 
  filter(word != 'sk') %>% 
  filter(word != 'yeah') %>% 
  filter(word != '')

wc_clean_11 <- wordcount_11 %>% 
  anti_join(stop_words, by = 'word') 

wc_clean_12 <- wordcount_12 %>% 
  anti_join(stop_words, by = 'word') 
wc_clean_13 <- wordcount_13 %>% 
  anti_join(stop_words, by = 'word') 

wc_clean_14 <- wordcount_14 %>% 
  anti_join(stop_words, by = 'word') 

wc_clean_15 <- wordcount_15 %>% 
  anti_join(stop_words, by = 'word') 

wc_clean_16 <- wordcount_16 %>% 
  anti_join(stop_words, by = 'word') %>% 
filter(word != 'mo') %>% 
  filter(word != 'td') %>% 
  filter(word != 'em') %>% 
  filter(word != 'yeah')
```

